---
- hosts: mongo_cluster
  remote_user: emerson
  roles:
  - mongo_common

- hosts: mongo_primary
  remote_user: emerson
  roles:
  - mongo_primary

#- hosts: mongo_secondary
#  remote_user: emerson
#  roles:
#  - mongo_secondary
